apiVersion: v1
kind: Service
metadata:
  name: mongo-express-ervice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30001
  selector:
    app: lab-app
    tier: ui
