apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
      tier: ui
  template:
    metadata:
      labels:
        app: lab-app
        tier: ui
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: root
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: helm-mongodb
                key: mongodb-root-password
          - name: ME_CONFIG_MONGODB_URL
            value: mongodb://root:$(ME_CONFIG_MONGODB_ADMINPASSWORD)@helm-mongodb-0.helm-mongodb-headless:27017,helm-mongodb-1.helm-mongodb-headless:27017?replicaSet=rs0
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: lab-app
    tier: ui
  type: LoadBalancer